#!/usr/bin/php
<?php
/**
 * @author stev leibelt <artodeto@bazzline.net>
 * @since 2015-02-07
*/
//delete
$command = 'rm -fr document/*';
passthru($command);

//generate
$options = array(
    '--source source/Net/Bazzline/Component/ProcessForkManager/',
    '--destination document/',
    '--title "Process Fork Manager by Bazzline"'
   );
$command = 'php vendor/bin/apigen generate ' . implode(' ', $options);
passthru($command);
